#!/bin/bash



#SBATCH -J "radparse_perl"
#SBATCH -o ../logs/RAD_cont_regions.txt
#SBATCH -c 20
#SBATCH -p cpu
#SBATCH --time=4:00:00
#SBATCH --mem=12000



module load gcc/11.2.0

#modify the perl script first for min Individuals and length. all.mafs file is generated by angsd upstream
 ../scripts_and_keyfiles/ParseMafs_commented.pl all.mafs
